AWSTemplateFormatVersion: '2010-09-09'
Description: DNS for blicksky.com

Parameters:
  DomainName:
    Type: String
    Default: blicksky.com

Mappings:
  RegionMap:
    us-east-1:
      S3HostedZoneId: Z3AQBSTGFYJSTF
      S3WebsiteEndpoint: s3-website-us-east-1.amazonaws.com

Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName

  RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZone
      RecordSets:
        - Name: !Ref DomainName
          Type: A
          AliasTarget:
            HostedZoneId: !FindInMap [RegionMap, !Ref 'AWS::Region', S3HostedZoneId]
            DNSName: !FindInMap [RegionMap, !Ref 'AWS::Region', S3WebsiteEndpoint]

        - Name: !Join ['', ['www.', !Ref DomainName]]
          Type: A
          AliasTarget:
            HostedZoneId: !FindInMap [RegionMap, !Ref 'AWS::Region', S3HostedZoneId]
            DNSName: !FindInMap [RegionMap, !Ref 'AWS::Region', S3WebsiteEndpoint]

        - Name: !Ref DomainName
          Type: MX
          TTL: '3600'
          ResourceRecords:
          - 1 aspmx.l.google.com.
          - 5 alt1.aspmx.l.google.com.
          - 5 alt2.aspmx.l.google.com.
          - 10 alt3.aspmx.l.google.com.
          - 10 alt4.aspmx.l.google.com.

Outputs:
  NameServers:
    Value: !Join [', ', !GetAtt HostedZone.NameServers]
